/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package database;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Bisu-Calape
 */
public class Form extends javax.swing.JFrame {
    DefaultTableModel model;
    Object tablerow[][];
    String tablecol[] = {"ID","FIRSTNAME","LASTNAME","ADDRESS","GENDER"};
    
    /**
     * Creates new form Form
     */
     QueryProcessor process;
     
    public Form() {
        initComponents();
        process = new QueryProcessor();
        setTable();
        
        fname.setEnabled(false);
        lname.setEnabled(false);
        address.setEnabled(false);
        male.setEnabled(false);
        fmale.setEnabled(false);
        edit.setEnabled(false);
        delete_btn.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        fname = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        lname = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        address = new javax.swing.JTextField();
        male = new javax.swing.JRadioButton();
        fmale = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Rtable = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        save = new javax.swing.JButton();
        edit = new javax.swing.JButton();
        delete_btn = new javax.swing.JButton();
        NewB = new javax.swing.JButton();
        ClearB = new javax.swing.JButton();
        lname_error = new javax.swing.JLabel();
        fname_error = new javax.swing.JLabel();
        address_error = new javax.swing.JLabel();
        gender_error = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Registration Form");

        jLabel2.setText("Firstname:");

        fname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fnameActionPerformed(evt);
            }
        });

        jLabel3.setText("Lastname:");

        jLabel4.setText("Address:");

        buttonGroup1.add(male);
        male.setText("Male");

        buttonGroup1.add(fmale);
        fmale.setText("Female");

        jLabel5.setText("Gender:");

        Rtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Rtable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RtableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Rtable);

        jLabel6.setText("Registered People");

        save.setText("SAVE");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });

        edit.setText("Edit");
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });

        delete_btn.setText("delete");
        delete_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_btnActionPerformed(evt);
            }
        });

        NewB.setText("New");
        NewB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewBActionPerformed(evt);
            }
        });

        ClearB.setText("Clear");
        ClearB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearBActionPerformed(evt);
            }
        });

        lname_error.setForeground(new java.awt.Color(255, 0, 0));

        fname_error.setForeground(new java.awt.Color(204, 0, 0));

        address_error.setForeground(new java.awt.Color(255, 0, 0));

        gender_error.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(195, 195, 195))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(fname, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(address, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                                    .addComponent(fname_error, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(address_error, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel5)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(207, 207, 207)
                                    .addComponent(lname_error, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGap(87, 87, 87)
                                    .addComponent(jLabel1)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(gender_error, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(male)
                                                .addGap(33, 33, 33)
                                                .addComponent(fmale))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGap(35, 35, 35)
                                                .addComponent(lname, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGap(35, 35, 35)))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(NewB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(save, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(edit)
                        .addGap(42, 42, 42)
                        .addComponent(delete_btn)
                        .addGap(18, 18, 18)
                        .addComponent(ClearB)))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lname_error, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fname_error, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(fname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(lname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(address_error, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(gender_error, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(address, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(male)
                    .addComponent(fmale)
                    .addComponent(jLabel5))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(save, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(edit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(delete_btn)
                    .addComponent(NewB)
                    .addComponent(ClearB))
                .addGap(13, 13, 13)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fnameActionPerformed

    private void RtableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RtableMouseClicked
       edit.setEnabled(true);
       delete_btn.setEnabled(true);
        int y = getRowNumber();
        setDataToTextFields(y);
        
    }//GEN-LAST:event_RtableMouseClicked

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
       // TODO add your handling code here:
        String gen=null;
        if(male.isSelected()){
            gen="Male";
        }if(fmale.isSelected()){
            gen="Female";
        }
        int x=0;
        if(gen==null){
            gender_error.setText("Gender is required.");
            x++;
        }
        if(fname.getText().isEmpty()){
            fname_error.setText("Firstname is required.");
            x++;
        }
        if (lname.getText().isEmpty()){
            lname_error.setText("Lastname is required.");
            x++;
        }
        if(address.getText().isEmpty()){
            
            address_error.setText("Address is required");
            x++;
        }
       
            if(x==0) {
        addInfo(gen);
        edit.setEnabled(false); 
        delete_btn.setEnabled(false);
        clearField();
        address_error.setText("");
         lname_error.setText("");
          gender_error.setText("");
           fname_error.setText("");
        }
    }//GEN-LAST:event_saveActionPerformed

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
         String gen=null;
        if(male.isSelected()){
            gen="Male";
        }if(fmale.isSelected()){
            gen="Female";
        }
        int id = getRowNumber();
        if(fname.getText().trim().isEmpty()||lname.getText().trim().isEmpty()||address.getText().trim().isEmpty()||gen!="Male"&&gen!="Female"){
           JOptionPane.showMessageDialog(null, "Please Complete the Form");
       }
        else{
            updateInfo(gen,id);
            clearField();
            edit.setEnabled(false);
            delete_btn.setEnabled(false);
            
        }
    }//GEN-LAST:event_editActionPerformed

    private void delete_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_btnActionPerformed
        // TODO add your handling code here:
        
        int id = getRowNumber();
        deleteInfo(id);
        
    }//GEN-LAST:event_delete_btnActionPerformed

    private void NewBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewBActionPerformed
        // TODO add your handling code here:
        fname.setEnabled(true);
        lname.setEnabled(true);
        address.setEnabled(true);
        male.setEnabled(true);
        fmale.setEnabled(true);
        edit.setEnabled(false);
    }//GEN-LAST:event_NewBActionPerformed

    private void ClearBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearBActionPerformed
        // TODO add your handling code here:
        clearField();
    }//GEN-LAST:event_ClearBActionPerformed
    
    public void clearField(){
        fname.setText(null);
        lname.setText(null);
        address.setText(null);
        buttonGroup1.clearSelection();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form().setVisible(true);
                 
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ClearB;
    private javax.swing.JButton NewB;
    private javax.swing.JTable Rtable;
    private javax.swing.JTextField address;
    private javax.swing.JLabel address_error;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton delete_btn;
    private javax.swing.JButton edit;
    private javax.swing.JRadioButton fmale;
    private javax.swing.JTextField fname;
    private javax.swing.JLabel fname_error;
    private javax.swing.JLabel gender_error;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField lname;
    private javax.swing.JLabel lname_error;
    private javax.swing.JRadioButton male;
    private javax.swing.JButton save;
    // End of variables declaration//GEN-END:variables
 
 private void addInfo(String gender) { //add data to database
       
     process.executeUpdate("Insert into `my_table` values(NULL,'"+fname.getText()+"','"+lname.getText()+"','"+address.getText()+"','"+gender+"') ");
         setTable();
       
    }
 private void updateInfo(String gender,int id) { // update data in database
      process.executeUpdate("UPDATE `my_table` SET `fname`='"+fname.getText()+"',`lname`='"+lname.getText()+"',`address`='"+address.getText()+"',`gender`='"+gender+"' WHERE  `id`='"+id+"'");
         setTable();
    }
 private void setTable() { //set data from database to prooject table
    tablerow =process.getAllRecord("Select * from `my_table`");
    model = new DefaultTableModel(tablerow,tablecol);
    Rtable.setModel(model); 
    }
 
 private int getRowNumber() { // get id from selected table

     return Integer.parseInt(model.getValueAt(Rtable.getSelectedRow(),0).toString());

 }
  private void setDataToTextFields(int id) { // get specific value in database and set to textfields
     //To change body of generated methods, choose Tools | Templates.
    fname.setText(process.getSpecificField("Select `fname` from `my_table` where `id`='"+id+"'"));
    lname.setText(process.getSpecificField("Select `lname` from `my_table` where `id`='"+id+"'"));
    address.setText(process.getSpecificField("Select `address` from `my_table` where `id` ='"+id+"'"));
    String g=process.getSpecificField("Select `gender` from `my_table` where `id` = '"+id+"'");
   
    if(g.equals("Male")){
        male.setSelected(true);
        fmale.setSelected(false);
    }if(g.equals("Female")){
        fmale.setSelected(true);
        male.setSelected(false);
    }
}
  private void deleteInfo(int record_id){//deleting record from database
      process.executeUpdate("DELETE FROM `my_table` where `id`='"+record_id+"' ");
      setTable();
      
  }

   
}
